server:
  port: 0


spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  profiles:
    active: dev

  rabbitmq:
    host: *
    port: 0
    username: *
    password: *
    mandatory:
      template: true
    #开启发送失败返回
    publisher-returns: true
    #开启发送确认
    #消费端配置
    listener:
      simple:
        #消费端
        concurrency: 5
        #最大消费端数
        max-concurrency: 10
        #自动签收auto  手动 manual
        acknowledge-mode: manual
        #限流（海量数据，同时只能过来一条）
        prefetch: 1
#日志
logging:
  config: classpath:logback-spring.xml
